# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Build go server
        run: |
          go build ./cmd/api
      
      - name: Build angular app
        uses: actions/setup-node@v3
        with:
          node-version: '14'

        run: |
          npm i &&
          cd angular && 
          ng build &&
          npx scully && 
          cd ../


